data <- read.delim('household_power_consumption.txt', sep=';', na.string='?', stringsAsFactors=FALSE)
data$DateTime <- strptime(paste(data$Date, data$Time), format='%d/%m/%Y %H:%M:%S')
sub_data <- subset(data, Date == '1/2/2007' | Date == '2/2/2007')
plot(sub_data$DateTime, sub_data$Sub_metering_1, xlab='', ylab='Energy sub meetering', type='n')
lines(sub_data$DateTime, sub_data$Sub_metering_1)
lines(sub_data$DateTime, sub_data$Sub_metering_2, col='red')
lines(sub_data$DateTime, sub_data$Sub_metering_3, col='blue')
legend('topright', c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lty=1, col=c('black','red','blue'))
png('plot3.png', width=480, height=480)
plot(sub_data$DateTime, sub_data$Sub_metering_1, xlab='', ylab='Energy sub meetering', type='n')
lines(sub_data$DateTime, sub_data$Sub_metering_1)
lines(sub_data$DateTime, sub_data$Sub_metering_2, col='red')
lines(sub_data$DateTime, sub_data$Sub_metering_3, col='blue')
legend('topright', c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lty=1, col=c('black','red','blue'))
dev.off()