data <- read.delim('household_power_consumption.txt', sep=';', na.string='?', stringsAsFactors=FALSE)
data$DateTime <- strptime(paste(data$Date, data$Time), format='%d/%m/%Y %H:%M:%S')
sub_data <- subset(data, Date == '1/2/2007' | Date == '2/2/2007')
plot(sub_data$DateTime, sub_data$Global_active_power, xlab='', ylab='Global Active Power (kilowatts)', type='n')
lines(sub_data$DateTime, sub_data$Global_active_power)
png('plot2.png', width=480, height=480)
plot(sub_data$DateTime, sub_data$Global_active_power, xlab='', ylab='Global Active Power (kilowatts)', type='n')
lines(sub_data$DateTime, sub_data$Global_active_power)
dev.off()